name: getx_binding_annotation_generator
description: A Code Generator Plugin to Generate Pages and Dependencies for GetX State Manager base on Annotation. (Generator)
version: 0.3.0
homepage: https://resam.site
repository: https://github.com/reesaam/flutter_getx_dependencies_binding_annotation.git
funding:
  - https://resam.site

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.10.4
  analyzer: ^8.1.1
  build: ^4.0.0
  source_gen: ^4.0.1
  dart_style: ^3.0.1
#  getx_binding_annotation: ^0.3.0
  getx_binding_annotation:
    path: ../annotation/

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0