name: example_for_getx_binding_annotation
description: A project used to demo the GetxDependenciesBindingAnnotation
version: 0.3.0
homepage: https://www.linkedin.com/in/resam/
repository: https://github.com/reesaam/flutter_getx_dependencies_binding_annotation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  getx_binding_annotation:
    path: ../../annotation/

dev_dependencies:
  build_runner: ^2.10.4
#  dartdoc: ^8.3.2
  lints: ^4.0.0
  test: ^1.24.0
  getx_binding_annotation_generator:
    path: ../../generator/