name: getx_binding_annotation
description: A Code Generator Plugin to Generate Pages and Dependencies for GetX State Manager base on Annotation.
version: 0.3.0
homepage: https://resam.site
repository: https://github.com/reesaam/flutter_getx_dependencies_binding_annotation.git
funding:
  - https://resam.site

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.10.4
#  dartdoc: ^8.3.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0